### PR TITLE
minor fixes (vbrev in zvkb list) + zvksed in DIEL

### PR DESCRIPTION
**Pull request by nibrunieAtSi5**
Another small set of suggested fixes for your consideration @kdockser

### CODE REVIEW

**Comment by nibrunieAtSi5** [comment]
I am not sure about the `vbrev` in `Zvkb` but since the link was added in https://github.com/riscv/riscv-crypto/commit/c1c70674d2d98fa179b7cd610f25ffcd1728bf85 I figured it should be in there.

**Review by kdockser — COMMENTED** [review]
As I recall, vbrev.v was not a part of the original vector crypto bitmanip. Only vrev8 and vbrev8 are required.

**Comment by nibrunieAtSi5** [comment]
Ok I will update both the Zvkb description and vbrev description then

**Comment by nibrunieAtSi5** [comment]
@kdockser, done, could you review this PR once again.

**Review by kdockser — APPROVED** [review]

**Pull request merged**
